language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6  # current default Python for Travis-CI
  - 3.7
  - 3.8
  - 3.9
install:
  - "python setup.py install"
  - "pip install coveralls"
script:
  - "nosetests --with-coverage --cover-package=jaconvV2"
after_success:
  - coveralls
